server:
  port: 5353

spring:
  datasource:
    url: jdbc:mysql://jph-dev.cincpgqgykpl.ap-northeast-2.rds.amazonaws.com:3306/jph
    username: jeekim
    password: wlzla01!

infotech:
  host: https://apigw.infotech.co.kr/api/service
  apiKey: 52de65a9-325a-407e-9403-29f210970559
kims:
  host: https://poc-api.kims.co.kr
  username: abc
  secret: def

springdoc:
  packages-to-scan: com.jeekim.server.jphappapi.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    display-request-duration: true
    operations-sorter: alpha
naver:
  storage:
    endPoint: https://kr.object.ncloudstorage.com
    regionName: kr-standard
    access-key: hU1bm8Mnp0XUo8TocewP
    secret-key: NOReFfYm3RFrxYN9vmiAWTN5Lzz1r4LyKNr8kdJc
    bucketName: jph-dev
feign:
  client:
    config:
      default:
        loggerLevel: FULL
logging:
  level:
    com.jeekim.server.jphappapi.client: DEBUG

lomin:
  email: guest@lomin.ai
  password: 123456
  baseUrl: https://api.textscope.ai/jeekim/stage/api/v1


---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://jph.cincpgqgykpl.ap-northeast-2.rds.amazonaws.com:3306/jph

naver:
  storage:
    bucketName: jph

infotech:
  apiKey: d2935130-0411-4775-8164-93c28ed7b335

lomin:
  baseUrl: https://api.textscope.ai/jeekim/prod/api/v1